Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-080e1f13689e07408
      Tags:
        - Key: "Name"
          Value: !Join 
            - " "
            - - "My Instance in"
              - !Ref AWS::Region


            #Intrinsic Function

